package com.logan.placefinder.service;

import java.util.List;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.logan.placefinder.dto.CreateFavouriteRequest;
import com.logan.placefinder.dto.FavouritePlaceResponse;
import com.logan.placefinder.entity.FavouritePlace;
import com.logan.placefinder.exception.DuplicateFavouriteException;
import com.logan.placefinder.exception.FavouritePlaceNotFoundException;
import com.logan.placefinder.repository.FavouritePlaceRepository;

import jakarta.persistence.EntityManager;

@Service
@Transactional(readOnly = true)
public class FavouritePlaceService {

    private final FavouritePlaceRepository repository;
    private final EntityManager entityManager;

    public FavouritePlaceService(
            FavouritePlaceRepository repository,
            EntityManager entityManager) {

        this.repository = repository;
        this.entityManager = entityManager;
    }

    public List<FavouritePlaceResponse> getAllFavourites() {
        return repository
            .findAllByOrderByCreatedAtDesc()
            .stream()
            .map(FavouritePlaceResponse::fromEntity)
            .toList();
    }

    public FavouritePlaceResponse getFavouriteById(Long id) {
        FavouritePlace favouritePlace = repository
            .findById(id)
            .orElseThrow(
                () -> new FavouritePlaceNotFoundException(id)
            );

        return FavouritePlaceResponse.fromEntity(favouritePlace);
    }

    public FavouritePlaceResponse getFavouriteByPlaceId(
            String placeId) {

        FavouritePlace favouritePlace = repository
            .findByPlaceId(placeId)
            .orElseThrow(
                () -> FavouritePlaceNotFoundException
                    .forPlaceId(placeId)
            );

        return FavouritePlaceResponse.fromEntity(favouritePlace);
    }

    public boolean isFavourite(String placeId) {
        return repository.existsByPlaceId(placeId);
    }

    @Transactional
    public FavouritePlaceResponse createFavourite(
            CreateFavouriteRequest request) {

        if (repository.existsByPlaceId(request.placeId())) {
            throw new DuplicateFavouriteException(
                request.placeId()
            );
        }

        FavouritePlace favouritePlace = new FavouritePlace(
            request.placeId().trim(),
            request.name().trim(),
            normalizeAddress(request.address()),
            request.latitude(),
            request.longitude()
        );

        try {
            FavouritePlace saved =
                repository.saveAndFlush(favouritePlace);

            /*
             * created_at is generated by SQL Server using
             * SYSUTCDATETIME(), so refresh the entity to retrieve it.
             */
            entityManager.refresh(saved);

            return FavouritePlaceResponse.fromEntity(saved);

        } catch (DataIntegrityViolationException exception) {
            /*
             * Handles two simultaneous requests that both pass the
             * exists check before one reaches the unique constraint.
             */
            throw new DuplicateFavouriteException(
                request.placeId()
            );
        }
    }

    @Transactional
    public void deleteFavourite(Long id) {
        FavouritePlace favouritePlace = repository
            .findById(id)
            .orElseThrow(
                () -> new FavouritePlaceNotFoundException(id)
            );

        repository.delete(favouritePlace);
    }

    @Transactional
    public void deleteFavouriteByPlaceId(String placeId) {
        FavouritePlace favouritePlace = repository
            .findByPlaceId(placeId)
            .orElseThrow(
                () -> FavouritePlaceNotFoundException
                    .forPlaceId(placeId)
            );

        repository.delete(favouritePlace);
    }

    private String normalizeAddress(String address) {
        if (address == null || address.isBlank()) {
            return null;
        }

        return address.trim();
    }
}